version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
      
  build:
    commands:
      - echo "Building the application..."
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed successfully!"
      - cd ..
      
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
  discard-paths: no
  base-directory: backend

cache:
  paths:
    - backend/node_modules/**/*
