version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install

  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test
      
  build:
    commands:
      - echo "Building the application..."
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - backend/dist/**/*
    - backend/package.json
    - backend/package-lock.json
    - backend/node_modules/**/*
  discard-paths: no

cache:
  paths:
    - backend/node_modules/**/*
